---
- name: Pull Docker image of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image
      shell: docker pull visshall9/simplecalculator:latest
    - name: Running container
      shell: docker run -it -d --name calculator visshall9/simplecalculator